### PR TITLE
Adds mocking and tracing support

### PR DESCRIPTION
**Pull request by kobigurk**

### CODE REVIEW

**Comment by asinyagin** [comment]
@kobigurk hey, i get an error: `SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`. Looks like node.js v4 doesn't support `let` without `strict`. It's a recommended version currently, so can you please fix that?

**Comment by kobigurk** [comment]
Done. Tested now with node v4.4.3. Can you check now?

**Comment by asinyagin** [comment]
Are you sure you've committed the changes?

**Comment by kobigurk** [comment]
Yeah, I overwrote the commit.

**Comment by asinyagin** [comment]
Cool. It works! The only thing: add web3 to workbench's package.json please. It uses web3 but doesn't have it in the dependencies.

**Comment by kobigurk** [comment]
Oops! Here you go.

**Pull request merged**
