### PR TITLE
Adds warning on undefined result in then and calls are sync

### PR DESCRIPTION
**Pull request by kobigurk**

### CODE REVIEW

**Comment by asinyagin** [comment]
@kobigurk hey, `npm test` fails on Proxy.sol compilation:

```
Proxy.sol:34:7: Warning: Return value of low-level calls not used.
      target.call(operation.data);
      ^-------------------------^
```

**Comment by kobigurk** [comment]
Seems like a change in solc 0.3.6 that verifies returns from low-level calls.
I modified the Proxy contract to ignore that as we don't mind, but keep in mind it also broke the official MultiSig contract from compiling. Modified that as well.

**Comment by asinyagin** [comment]
Cool. That warning was added in 0.3.5.

**Comment by asinyagin** [comment]
Yeah, solc-js has started showing the warning only in 0.3.6. Also, now it gives all the standard contracts in `output.sources` and deployment of predefined contracts fails because of that. Need to fix that first.

**Pull request merged**
